name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # ← your WSL machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy
        run: |
          cd ~/springboot-mongo-crud
          git pull origin main
          docker compose down
          docker compose up --build -d
